<a href="https://colab.research.google.com/github/MulanSchneeberg/Deep-Learning-With-Python/blob/master/Copy_of_Chapter_3_5_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3.5.1 Constant tensors and variables
To do anything with TensorFlow, we need tensors. Tensors need to be created with some initial values
e.g.
- all-ones or all-zeros
- or tensers of values drawn from a random distribution

In [ ]:
import tensorflow as tf
x=tf.ones(shape=(2,1)) # equivalent to np.ones(shape=(2,1))
print(x)


tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [ ]:
x=tf.zeros(shape=(2,1))
print(x)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


##Random tensors

### Tensors of random values drawn from a normal distribution with mean 0 and standard deviation 1. 
### Equivalent to `np.random.normal(size=(3,1), loc=0., scale=1.)`

In [ ]:
x=tf.random.normal(shape=(3,1), mean=0., stddev=1.)
print(x)

tf.Tensor(
[[-0.48020062]
 [ 2.0937977 ]
 [ 1.1061234 ]], shape=(3, 1), dtype=float32)


### Tensors of random values drawn from a uniform distribution between 0 and 1.
### Equivalent to `np.random.normal(size=(3,1), low=0., high=1.)`

In [ ]:
x=tf.random.uniform(shape=(3,1), minval=0., maxval=1.)
print(x)

tf.Tensor(
[[0.8910471 ]
 [0.7716458 ]
 [0.03403234]], shape=(3, 1), dtype=float32)


## Create Tensor variables
### Create variables: To create a variable, you need to provide some initial value, such as a random tensor.

In [ ]:
v=tf.Variable(initial_value=tf.random.normal(shape=(3,1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.4253992 ],
       [0.08583429],
       [0.20478594]], dtype=float32)>


### The state of a variable can be modified via its assign method, as follows.

In [ ]:
v.assign(tf.ones(shape=(3,1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>


### Or work o subsets of the coeffcients

In [ ]:
v[0, 0].assign(3)

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [2.],
       [2.]], dtype=float32)>

### `assign_add()` and `assign_sub()` are += and -=

In [ ]:
v.assign_add(tf.ones((3,1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [3.],
       [3.]], dtype=float32)>

# 3.5.2 Tensor operations: Doing math in TensorFlow

In [ ]:
a=tf.ones((2,2))
b=tf.square(a)
c=tf.sqrt(a)
d=b+c
e=tf.matmul(a,b) # Take the product of two tensors
e *=d

# 3.5.3 GradientTape API

### Just open a `GradientTape` scope, apply some computation to one or several input tensors, and reetrieve the gradient of the result with respect to the inputs.
### his is most commonly used to retrieve the gradients of the loss of a model with respect to its weights: `gradients = tape.gradient(loss, weights)`
.


In [ ]:
# Using GradientTape
input_var=tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
  result=tf.square(input_var)
gradient=tape.gradient(result,input_var)
print(gradient)
  

tf.Tensor(6.0, shape=(), dtype=float32)


### so far, you’ve only seen the case where the input tensors in `tape.gradient()` were TensorFlow variables. It’s actually possible for these inputs to be any arbitrary tensor. However, only trainable variables are tracked by default. With a constant tensor, you’d have to manually mark it as being tracked by calling `tape.watch()` on it.

In [ ]:
# Using GradientTape with constant tensor inputs
input_const=tf.constant(3.)
with tf.GradientTape() as tape:
  tape.watch(input_const)
  result=tf.square(input_const)
gradient=tape.gradient(result,input_const)
print(gradient)

tf.Tensor(6.0, shape=(), dtype=float32)


In [ ]:
# USing nested gradient tapes to compute second-order gradients
time=tf.Variable(0.)
with tf.GradientTape() as outer_tape:
  with tf.GradientTape() as inner_tape:
    position=4.9*time**2
  speed=inner_tape.gradient(position, time)
acceleration=outer_tape.gradient(speed, time)
print(acceleration)


tf.Tensor(9.8, shape=(), dtype=float32)
